## Concatenate following arrays along axis=0


In [6]:
import numpy as np
  
x=np.array([[1,2],[3,4]])
y=np.array([[5,6]])
  
Conc_Arr = np.concatenate((x, y), axis = 0)
print("x-\n",x)
print("y-\n",y)
print ('\nConcatenated array-\n',Conc_Arr)

x-
 [[1 2]
 [3 4]]
y-
 [[5 6]]

Concatenated array-
 [[1 2]
 [3 4]
 [5 6]]
