## Create a random vector of size 30 and find the mean value.


In [6]:
import numpy as np
Array = np.random.random((5,6))
print('Array-\n',Array)
Mean=np.mean(Array)

print('\nMean of array -',Mean)

Array-
 [[0.49040871 0.86144284 0.38704153 0.03682602 0.50544431 0.65885287]
 [0.60164603 0.49035661 0.62783591 0.22047812 0.39718869 0.91216046]
 [0.57301783 0.20087381 0.0926032  0.05645792 0.47048152 0.51164412]
 [0.25232932 0.44612419 0.88239861 0.6102877  0.62835528 0.98411966]
 [0.46946409 0.19049947 0.8597643  0.97191939 0.3073485  0.99980482]]

Mean of array - 0.5232391937166885
